/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samuelflores_lab6;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samuel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        inv.cargarArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarproducto = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_producto1 = new javax.swing.JComboBox<>();
        tf_nombre1 = new javax.swing.JTextField();
        tf_precioventa1 = new javax.swing.JTextField();
        tf_preciocosto1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenu2 = new javax.swing.JMenu();
        jd_listarproducto = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jd_modificaryeliminar = new javax.swing.JDialog();
        cb_mye = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jd_factura = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_cai = new javax.swing.JTextField();
        tf_fecha = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_clientes = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_rtn = new javax.swing.JTextField();
        jd_ingresar = new javax.swing.JDialog();
        jd_ventas = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_fecha1 = new javax.swing.JTextField();
        tf_totaldeventas = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jd_ingresos = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jLabel5.setText("Precio costo");

        jLabel6.setText("Precio venta");

        jLabel7.setText("Nombre");

        jLabel8.setText("Producto");

        cb_producto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Bebida" }));

        jButton2.setText("Agregar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarproductoLayout = new javax.swing.GroupLayout(jd_agregarproducto.getContentPane());
        jd_agregarproducto.getContentPane().setLayout(jd_agregarproductoLayout);
        jd_agregarproductoLayout.setHorizontalGroup(
            jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarproductoLayout.createSequentialGroup()
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_preciocosto1)
                            .addComponent(tf_precioventa1)
                            .addComponent(tf_nombre1)
                            .addComponent(cb_producto1, 0, 162, Short.MAX_VALUE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarproductoLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(23, 23, 23))))
        );
        jd_agregarproductoLayout.setVerticalGroup(
            jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_preciocosto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_precioventa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_producto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jMenu2.setText("jMenu2");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio ", "Precio de venta"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Listar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listarproductoLayout = new javax.swing.GroupLayout(jd_listarproducto.getContentPane());
        jd_listarproducto.getContentPane().setLayout(jd_listarproductoLayout);
        jd_listarproductoLayout.setHorizontalGroup(
            jd_listarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarproductoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jd_listarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jd_listarproductoLayout.setVerticalGroup(
            jd_listarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarproductoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        cb_mye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modificar", "Eliminar" }));

        jButton3.setText("Avanzar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificaryeliminarLayout = new javax.swing.GroupLayout(jd_modificaryeliminar.getContentPane());
        jd_modificaryeliminar.getContentPane().setLayout(jd_modificaryeliminarLayout);
        jd_modificaryeliminarLayout.setHorizontalGroup(
            jd_modificaryeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificaryeliminarLayout.createSequentialGroup()
                .addGroup(jd_modificaryeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificaryeliminarLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(cb_mye, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificaryeliminarLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton3)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jd_modificaryeliminarLayout.setVerticalGroup(
            jd_modificaryeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificaryeliminarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cb_mye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jButton3)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jLabel1.setText("CAI");

        jLabel2.setText("Fecha");

        jLabel3.setText("Correo");

        jLabel4.setText("Clientes");

        jButton4.setText("Facturar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel9.setText("RTN");

        javax.swing.GroupLayout jd_facturaLayout = new javax.swing.GroupLayout(jd_factura.getContentPane());
        jd_factura.getContentPane().setLayout(jd_facturaLayout);
        jd_facturaLayout.setHorizontalGroup(
            jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_facturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(jd_facturaLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_cai)
                    .addComponent(tf_fecha)
                    .addComponent(tf_correo)
                    .addComponent(tf_clientes)
                    .addComponent(tf_rtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jd_facturaLayout.setVerticalGroup(
            jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_facturaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_cai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_rtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_ingresarLayout = new javax.swing.GroupLayout(jd_ingresar.getContentPane());
        jd_ingresar.getContentPane().setLayout(jd_ingresarLayout);
        jd_ingresarLayout.setHorizontalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_ingresarLayout.setVerticalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel10.setText("Fecha");

        jLabel11.setText("Total de ventas");

        jButton5.setText("Archivo ingresos");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ventasLayout = new javax.swing.GroupLayout(jd_ventas.getContentPane());
        jd_ventas.getContentPane().setLayout(jd_ventasLayout);
        jd_ventasLayout.setHorizontalGroup(
            jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ventasLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(tf_totaldeventas))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ventasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(31, 31, 31))
        );
        jd_ventasLayout.setVerticalGroup(
            jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ventasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_totaldeventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(31, 31, 31))
        );

        jButton6.setText("Generar archivo de Ingresos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ingresosLayout = new javax.swing.GroupLayout(jd_ingresos.getContentPane());
        jd_ingresos.getContentPane().setLayout(jd_ingresosLayout);
        jd_ingresosLayout.setHorizontalGroup(
            jd_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresosLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jd_ingresosLayout.setVerticalGroup(
            jd_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresosLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Dunkin Donuts");

        jMenu3.setText("Producto");

        jMenuItem6.setText("Agregar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Listar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Modificar y eliminar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenu1.add(jMenu3);

        jMenuItem2.setText("Inventario");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Factura");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Ventas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Ingresos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            String prod = cb_producto1.getSelectedItem().toString();
            if (prod.equals("Comida")) {
                String tipodecomida = JOptionPane.showInputDialog("Ingrese el tipo de comida: ");
                inv.getInventario().add(new Comida(tipodecomida, Double.parseDouble(tf_preciocosto1.getText()), Double.parseDouble(tf_precioventa1.getText()), tf_nombre1.getText()));
                inv.escribirArchivo();

            } else if (prod.equals("Bebida")) {
                String estado = JOptionPane.showInputDialog("Ingrese el estado: ");
                String tipo = JOptionPane.showInputDialog("Ingrese el tipo: ");
                String tamano = JOptionPane.showInputDialog("Ingrese el tamano: ");
                inv.getInventario().add(new Bebida(estado, tamano, tipo, Double.parseDouble(tf_preciocosto1.getText()), Double.parseDouble(tf_precioventa1.getText()), tf_nombre1.getText()));
                inv.escribirArchivo();
            }
        } catch (Exception e) {
            System.out.println("OCURRIO UN PROBLEMA");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jd_agregarproducto.pack();
        jd_agregarproducto.setLocationRelativeTo(this);
        jd_agregarproducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jd_listarproducto.pack();
        jd_listarproducto.setLocationRelativeTo(this);
        jd_listarproducto.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        for (int i = 0; i < inv.getInventario().size(); i++) {
            Object[] newrow = {
                inv.getInventario().get(i).getNombre(), 
                inv.getInventario().get(i).getPreciocosto(), inv.getInventario().get(i).getPreciodeventa()
            };
            model.addRow(newrow);

        }
        tabla.setModel(model);
      
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jd_modificaryeliminar.pack();
        jd_modificaryeliminar.setLocationRelativeTo(this);
        jd_modificaryeliminar.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String eyl;
        eyl = cb_mye.getSelectedItem().toString();
        if (eyl.equals("Modificar")) {
            String salida = "";
            for (Producto t : inv.getInventario()) {
                if (t instanceof Producto) {
                    salida += inv.getInventario().indexOf(t) + " ";
                    salida += t + "\n";
                }
                JOptionPane.showMessageDialog(null, salida);

            }
            String po = JOptionPane.showInputDialog("Ingrese la posicion a modificar: ");
            int pos = Integer.parseInt(po);
            String op=JOptionPane.showInputDialog("a-Comida\n"
                    + "b-Bebida");
            switch(op){
                case"a":
                    String op1 = JOptionPane.showInputDialog("a-Nombre\n"
                            + "b-Precio de costo\n"
                            + "c-Precio de venta\n"
                            + "d-Tipo de comida");
                    switch(op1){
                        case"a":
                            String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                            ((Comida)inv.getInventario().get(pos)).setNombre(nombre);
                            break;
                        case "b":
                            String preciocosto = JOptionPane.showInputDialog("Ingrese un precio de costo: ");
                            double preciocost = Double.parseDouble(preciocosto);
                            ((Comida)inv.getInventario().get(pos)).setPreciocosto(preciocost);
                            break;
                        case "c":
                            String precioventa = JOptionPane.showInputDialog("Ingrese el precio de venta: ");
                            double precioven= Double.parseDouble(precioventa);
                            ((Comida)inv.getInventario().get(pos)).setPreciodeventa(precioven);
                            break;
                        case "d":
                            String tipodecomida = JOptionPane.showInputDialog("Ingrese el tipo de comida: ");
                            ((Comida)inv.getInventario().get(pos)).setTipocomida(tipodecomida);
                            break;
                            
                    }
                    break;
                case"b":
                     String op2 = JOptionPane.showInputDialog("a-Estado\n"
                            + "b-Tamano\n"
                            + "c-Tipo\n"
                            + "d-Precio costo\n"
                             + "e-Precio venta\n"
                             + "f-Nombre");
                    switch(op2){
                        case "a":
                            String estado = JOptionPane.showInputDialog("Ingrese el estado: ");
                            ((Bebida)inv.getInventario().get(pos)).setEstado(estado);
                            break;
                        case "b":
                            String tamano = JOptionPane.showInputDialog("Ingrese el tamano: ");
                            ((Bebida)inv.getInventario().get(pos)).setTamano(tamano);
                            break;
                        case "c":
                            String tipo = JOptionPane.showInputDialog("Ingrese el tipo: ");
                            ((Bebida)inv.getInventario().get(pos)).setTipo(tipo);
                            break;
                        case "d":
                            String preciocosto = JOptionPane.showInputDialog("Ingrese un precio de costo: ");
                            double preciocost = Double.parseDouble(preciocosto);
                            ((Bebida)inv.getInventario().get(pos)).setPreciocosto(preciocost);
                            break;
                        case "e":
                            String precioventa = JOptionPane.showInputDialog("Ingrese el precio de venta: ");
                            double precioven= Double.parseDouble(precioventa);
                            ((Bebida)inv.getInventario().get(pos)).setPreciodeventa(precioven);
                            break;
                        case "f":
                            String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
                            ((Bebida)inv.getInventario().get(pos)).setNombre(nombre);
                            break;
                        
                    }
                  
                    break;
            }
            
            

        } else if (eyl.equals("Eliminar")) {
            String salida = "";
            for (Producto t : inv.getInventario()) {
                if (t instanceof Producto) {
                    salida += inv.getInventario().indexOf(t) + " ";
                    salida += t + "\n";
                }
                JOptionPane.showMessageDialog(null, salida);

            }
            String po = JOptionPane.showInputDialog("Ingrese el producto que desea eliminar: ");
            int pos=Integer.parseInt(po);
            inv.getInventario().remove(pos);

        }
       inv.escribirArchivo();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Factura fac = new Factura( tf_correo.getText(),  tf_nombre1.getText(),  tf_rtn.getText(),  tf_cai.getText(),  tf_fecha.getText());
        fac.escribirArchivo(inv);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jd_factura.pack();
        jd_factura.setLocationRelativeTo(this);
        jd_factura.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jd_ingresos.pack();
        jd_ingresos.setLocationRelativeTo(this);
        jd_ingresos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jd_ventas.pack();
        jd_ventas.setLocationRelativeTo(this);
        jd_ventas.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        ing.escribirArchivo();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
       ing.getIng().add(new Ventas(Double.parseDouble(tf_totaldeventas.getText()),tf_fecha1.getText()));
        
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_mye;
    private javax.swing.JComboBox<String> cb_producto1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_agregarproducto;
    private javax.swing.JDialog jd_factura;
    private javax.swing.JDialog jd_ingresar;
    private javax.swing.JDialog jd_ingresos;
    private javax.swing.JDialog jd_listarproducto;
    private javax.swing.JDialog jd_modificaryeliminar;
    private javax.swing.JDialog jd_ventas;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tf_cai;
    private javax.swing.JTextField tf_clientes;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_fecha;
    private javax.swing.JTextField tf_fecha1;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_preciocosto1;
    private javax.swing.JTextField tf_precioventa1;
    private javax.swing.JTextField tf_rtn;
    private javax.swing.JTextField tf_totaldeventas;
    // End of variables declaration//GEN-END:variables
Inventario inv = new Inventario("./Inventario.txt");
Ingresos ing = new Ingresos();
}
